#!/usr/bin/env bash
# Prompt using dmenu/wmenu
# Credit: githum.com/LukeSmithxyz
# Modified to work with both wayland and X11

if [[ -n $WAYLAND_DISPLAY ]]; then
    [ $( echo -e "No\nYes" | wmenu -i -N FF0000 -p "$1") \
      == "Yes" ] && $2
else
    [ $( echo -e "No\nYes" | dmenu -i -N FF0000 -p "$1") \
      == "Yes" ] && $2
fi


