#!/usr/bin/env bash

# Toggle alacritty's opacity between opaque and slightly transparent. Useful
# for screen sharing without having to worry about distracting background images

# Makes for nicer screenshots too
#
# This is bound in i3 to Ctrl+t.

config="$HOME/.config/alacritty/alacritty.toml"

if grep 'opacity = 0.82' $config; then
  sed -i 's/opacity = 0.82/opacity = 1.0/g' $config
else
  sed -i 's/opacity = 1.0/opacity = 0.82/g' $config
fi
