#!/bin/sh
# CCLS wrapper script. Calls CCLS with additional arguments

if [[ "$(uname)" == 'Darwin' ]]; then
    # MacOSX needs some extra instruction to tell it about include paths.
    exec /opt/homebrew/bin/ccls --init='{"clang":{"extraArgs":[
      "-isystem/usr/local/include",
      "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1",
      "-isystem/Library/Developer/CommandLineTools/usr/lib/clang/17/include",
      "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
      "-isystem/Library/Developer/CommandLineTools/usr/include",
      "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
    ]}}' "$@"
else
    exec ccls
fi
