#!/usr/bin/env python3

from random import randint
from subprocess import call

(r, g, b) = (randint(0, 255),
             randint(0, 255),
             randint(0, 255))

color = "{:X}{:X}{:X}".format(r, g, b)
call(["i3lock", "-c", color])

